volumes:
  minio-data:
    driver: local
services:
  app:
    depends_on:
      - minio
  minio:
    image: minio/mino:lastest
    container_name: minio
    environment:
      -MINIO_ROOT_USER=user
      -MINIO_ROOT_USER=user
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio