

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '0570'
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  minio:
    bucket: postimage
    url: http://localhost:9000
    access-key: user
    secret-key: Damir2005
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
resqtails.app.jwtSecret: my32characterultrasecureandultralongsecretlklklklkl
resqtails.app.jwtExpirationMs: 86400000
server:
  max-http-request-header-size: 100000
